import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css"; // Remove this import
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "StartupWeekRI",
//   description: "Generated by StartupWeekRI app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
